<a href="https://colab.research.google.com/github/Abhinavthirumalaiswamy/Luxury-housing-sales-analysis/blob/main/Luxury_housing_sales_analysis_mini_project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/Luxury_Housing_Bangalore (3).csv")
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29215187,Primary,Other,30-06-2024,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004,Secondary,CXO,31-12-2024,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.82937316,Primary,CXO,30-09-2024,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.18330315,Primary,NRI,31-12-2023,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.91415638,Secondary,Other,30-06-2024,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,31-12-2023,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [ ]:
# Removing duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# To handle missing values
df.dropna()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.89675235,Secondary,Other,31-03-2025,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99989,PROP099990,Kanakapura Road,Project_489,Total Environment,5261.0,5Bhk+,13.33416988,Primary,HNI,30-09-2024,9.039232,8.770910,Under construction,Direct,no,7.590715,60,Will buy after possession.
99990,PROP099991,Mg Road,Project_490,Sobha,3968.0,3bhk,13.8192586,Primary,HNI,30-06-2023,8.196025,6.061669,Under construction,Broker,no,8.414760,52,Agent was not responsive.
99991,PROP099992,jp nagar,Project_491,Godrej,6339.0,3bhk,12.4695383,Secondary,Startup Founder,30-09-2024,5.820541,9.779352,Under construction,Broker,yes,9.781777,31,Will buy after possession.
99993,PROP099994,SARJAPUR ROAD,Project_493,Tata Housing,7902.0,5Bhk+,₹12.55 Cr,Secondary,Other,31-12-2023,9.335818,8.489119,Under construction,Broker,no,8.849914,41,Underpriced for location.
99996,PROP099997,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.2720808,Secondary,Other,31-12-2023,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.

In [ ]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29215187,Primary,Other,30-06-2024,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.18519349,Primary,NRI,31-12-2023,8.379908,NaN,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,PROP099997,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.2720808,Secondary,Other,31-12-2023,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,PROP099998,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.73017863,Primary,Startup Founder,30-09-2023,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,NaN
99998,PROP099999,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.36398898,Primary,NRI,30-09-2024,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,NaN
99999,PROP100000,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.41561683,Primary,Startup Founder,30-09-2024,5.786292,5.284026,Launch,Broker,yes,6.039943,95,NaN

In [ ]:
# To create a data frame
df.to_csv("Luxury_Housing_Bangalore.csv",index = False)